name 'szynaka-syslog_ng'
version '1.0.0'

author 'Ed Szynaka <szynaka@loclnet.com>'
license 'Apache2'
project_page 'https://github.com/szynaka/syslog_ng'
source 'https://github.com/szynaka/syslog_ng'
summary 'Puppet module for syslog-ng'
description 'This module installs and manages syslog-ng. Check README for details.'
dependency 'example42/puppi', '>=2.0.0'
dependency 'example42/firewall', '>=2.0.0'
dependency 'example42/monitor', '>=2.0.0'
